### ISSUE TITLE
TODO: Documentation

### ISSUE THREAD

**Issue by fcampelo** [fcampelo/MOEADr#22]
- [ ] Write Vignette explaining how to define a MOEADr-compliant problem
- [ ] Write vignette explaining the variation stack
- [ ] Finish documentation of function moead()
